### ISSUE TITLE
gccversion of arm-current

### ISSUE THREAD

**Issue by slackpanos** [idlemoor/distcc-tools#1]
Hi David!
Maybe this: [ "$ARCH" = "arm" ] && GCCVERSION=5.2.1 must to change to && GCCVERSION=5.3.1 ?
Slackware-arm version of gcc is now at 5.3.1

**Comment by idlemoor** [comment]
I've finally found the time to update this before 14.2 happens, thanks for pointing out the problem and I hope you've not been waiting all this time!
